---
- name: Get disk facts
  community.windows.win_disk_facts:

- name: Output first disk size
  debug:
    var: ansible_facts.disks[0].size

- name: Convert first system disk into various formats
  debug:
    msg: '{{ disksize_gib }} vs {{ disksize_gib_human }}'
  vars:
    disk: '{{ ansible_facts.disks|selectattr("system_disk")|first }}'
    disksize_gib_human: '{{ disk.size|filesizeformat(true) }}'
    disksize_gib: '{{ (disk.size/1024|pow(3))|round|int }} GiB'
    disksize_gb_human: '{{ disk.size|filesizeformat }}'
    disksize_gb: '{{ (disk.size/1000|pow(3))|round|int }} GB'

- name: Output second disk serial number
  debug:
    var: ansible_facts.disks[1].serial_number

- name: Get disk physical_disk and partition facts on the target
  community.windows.win_disk_facts:
    filter:
      - physical_disk
      - partitions
