---
    
- block:
  - name: Resize Partitions
    community.windows.win_partition:
      drive_letter: "{{ item.drive_letter }}"
      partition_size: -1
      partition_number: "{{ item.partition_number }}"
      disk_number: "{{ item.disk_number }}"
    loop: "{{ host_vars.disks }}"
    when: item.partition_number is defined
    
  - name: Set success variable
    set_fact:
      resize_success: true
  rescue:
    - name: Set failure variable
      set_fact:
        resize_success: false
  always:

    - name: Ensure the destination directory exists
      local_action:
        module: file
        path: "{{ playbook_dir }}"
        state: directory

    - name: Write result to a file using template
      local_action:
        module: template
        src: "roles/windows_disk_management/templates/state.ini.j2"
        dest: "{{ playbook_dir }}/state.ini"
      vars:
        resize_success: "{{ resize_success | default('false') }}"

    - name: Write error-resize message to file using template
      local_action:
        module: template
        src: "roles/windows_disk_management/templates/error.ini.j2"
        dest: "{{ playbook_dir }}/error.ini"
      vars:
        error_message: "Resize Failed due to Size"