- name: Get disk facts
  community.windows.win_disk_facts:

- name: Display formatted disk information
  debug:
    msg: |
      ** Disk Information **
      {% for disk in ansible_facts.disks %}
      Disk Number: {{ disk.number }}
      Serial Number: {{ disk.serial_number }}
      ---------------------
      {% endfor %}
